version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1
workflows:
  build-and-deploy:
    jobs:
      - test:
          steps:
            - name: テストの実施
            - run: echo 'ダミーテスト実行'
      - aws-ecr/build_and_push_image:
          context:
            - dev-sandbox
          requires:
            - test
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "dev-sandbox-ecstest-repo"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master
      - aws-ecs/deploy-service-update:
          context:
            - dev-sandbox
          requires:
            - build-staging
          family: "codedeploy-sample-nginx"
          service-name: "codedeploy-sample-service"
          cluster-name: "DevSandboxSampleCluster"
          container-image-name-updates: "container=codedeploy-sample-nginx,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master
