version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1

jobs:
  build-and-test:
    executor: node
    steps:
      - checkout
      - run: echo 'Cacheの復元'
      - run: echo 'npm install'
      - run: echo 'Cacheの保存'
      - run: echo 'ダミーテスト実行'
      - run: echo 'テスト結果の保存'

workflows:
  build-and-deploy:
    jobs:
      - build-and-test
      - aws-ecr/build-and-push-image:
          context:
            - dev-sandbox
          requires:
            - build-and-test
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "dev-sandbox-ecstest-repo"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master
      - aws-ecs/deploy-service-update:
          context:
            - dev-sandbox
          requires:
            - build-staging
          family: "codedeploy-sample-nginx"
          service-name: "codedeploy-sample-service"
          cluster-name: "DevSandboxSampleCluster"
          container-image-name-updates: "container=codedeploy-sample-nginx,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master
